# -*- coding: utf-8 -*-

# nagios-check-hddtemp
# check_hddtemp.pyi

from typing import List, Dict, Union, Tuple  # pylint: disable=W0611

from argparse import Namespace

__all__: List[str] = ...

class CheckHDDTemp(object):

    OUTPUT_TEMPLATES: Dict[str, Dict[str, Union[str, int]]] = ...
    EXIT_CODES: Dict[str, int] = ...
    PERFORMANCE_DATA_TEMPLATE: str = ...
    def __init__(self) -> None: ...
    @staticmethod
    def get_options() -> Namespace: ...
    def get_data(self) -> str: ...
    def parse_response(self, response: str) -> Dict[str, Dict[str, str]]: ...
    def check_hddtemp(
        self, data: Dict[str, Dict[str, str]]
    ) -> Dict[str, Dict[str, Union[str, Dict[str, Union[None, int, str]]]]]: ...
    def output(
        self, states: Dict[str, Dict[str, Union[str, Dict[str, Union[None, int, str]]]]]
    ) -> Tuple[str, int]: ...
    def check(self) -> None: ...
