# -*- coding: utf-8 -*-

# nagios-check-hddtemp
# tests/check_hddtemp_test.pyi

from typing import List  # pylint: disable=W0611

from pytest_mock.plugin import MockerFixture

__all__: List[str] = ...

def test__check_data(mocker: MockerFixture) -> None: ...
def test__check_data__critical(mocker: MockerFixture) -> None: ...
def test__check_data__sleeping_device(mocker: MockerFixture) -> None: ...
def test__check_data__unknown_device(mocker: MockerFixture) -> None: ...
def test__check_data__unknown_device_temperature(mocker: MockerFixture) -> None: ...
def test__check_data__warning(mocker: MockerFixture) -> None: ...
def test__get_data(mocker: MockerFixture) -> None: ...
def test__get_data__network_error(mocker: MockerFixture) -> None: ...
def test__get_options(mocker: MockerFixture) -> None: ...
def test__get_options__missing_server_option(mocker: MockerFixture) -> None: ...
def test__get_options__warning_gte_critical(mocker: MockerFixture) -> None: ...
def test__get_output(mocker: MockerFixture) -> None: ...
def test__get_output__critical(mocker: MockerFixture) -> None: ...
def test__get_output__critical__performance_data(mocker: MockerFixture) -> None: ...
def test__get_output__performance_data(mocker: MockerFixture) -> None: ...
def test__get_output__sleeping(mocker: MockerFixture) -> None: ...
def test__get_output__sleeping__performance_data(mocker: MockerFixture) -> None: ...
def test__get_output__unknown_device(mocker: MockerFixture) -> None: ...
def test__get_output__unknown_device__performance_data(
    mocker: MockerFixture,
) -> None: ...
def test__get_output__unknown_device_temperature(mocker: MockerFixture) -> None: ...
def test__get_output__unknown_device_temperature__performance_data(
    mocker: MockerFixture,
) -> None: ...
def test__get_output__warning(mocker: MockerFixture) -> None: ...
def test__get_output__warning__performance_data(mocker: MockerFixture) -> None: ...
def test__get_status(mocker: MockerFixture) -> None: ...
def test__get_status__critical(mocker: MockerFixture) -> None: ...
def test__get_status__sleeping(mocker: MockerFixture) -> None: ...
def test__get_status__unknown_device(mocker: MockerFixture) -> None: ...
def test__get_status__unknown_device_temperature(mocker: MockerFixture) -> None: ...
def test__parse_data(mocker: MockerFixture) -> None: ...
def test__get_status__warning(mocker: MockerFixture) -> None: ...
def test__parse_data__parsing_error(mocker: MockerFixture) -> None: ...
def test__parse_data__too_short_error(mocker: MockerFixture) -> None: ...
def test_check(mocker: MockerFixture) -> None: ...
def test_check__critical(mocker: MockerFixture) -> None: ...
def test_check__critical__performance_data(mocker: MockerFixture) -> None: ...
def test_check__performance_data(mocker: MockerFixture) -> None: ...
def test_check__sleeping(mocker: MockerFixture) -> None: ...
def test_check__sleeping__performance_data(mocker: MockerFixture) -> None: ...
def test_check__unknown_device(mocker: MockerFixture) -> None: ...
def test_check__unknown_device__performance_data(mocker: MockerFixture) -> None: ...
def test_check__unknown_device_temperature(mocker: MockerFixture) -> None: ...
def test_check__unknown_device_temperature__performance_data(
    mocker: MockerFixture,
) -> None: ...
def test_check__warning(mocker: MockerFixture) -> None: ...
def test_check__warning__performance_data(mocker: MockerFixture) -> None: ...
def test_main(mocker: MockerFixture) -> None: ...
def test__get_code(mocker: MockerFixture) -> None: ...
def test__get_code__critical(mocker: MockerFixture) -> None: ...
def test__get_code__sleeping(mocker: MockerFixture) -> None: ...
def test__get_code__warning(mocker: MockerFixture) -> None: ...
def test__get_code__unknown_device(mocker: MockerFixture) -> None: ...
def test__get_code__unknown_device_temperature(mocker: MockerFixture) -> None: ...
